Content: Getting data ready, building model, fitting model to data, making predictions and evaluating a model, saving model and putting it all together.

In [2]:
import torch
from torch import nn
import matplotlib.pyplot as plt

Small linear regression model.

In [7]:
weight = 0.7
bias = 0.3

# Create data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias
train_data = torch.stack([X,y],dim=1)
X[:10], y[:10], train_data[:10]


(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]),
 tensor([[[0.0000],
          [0.3000]],
 
         [[0.0200],
          [0.3140]],
 
         [[0.0400],
          [0.3280]],
 
         [[0.0600],
          [0.3420]],
 
         [[0.0800],
          [0.3560]],
 
         [[0.1000],
          [0.3700]],
 
         [[0.1200],
          [0.3840]],
 
         [[0.1400],
          [0.3980]],
 
         [[0.1600],
          [0.4120]],
 
         [[0.1800],
          [0.4260]]]))

In [8]:
from torch.utils.data import random_split
train_split = int(0.8*len(X))
train, test =   random_split(train_data,[train_split,len(X)-train_split])

In [10]:
train

In [9]:
def plot_predictions(train_data=train[:,0], 
                     train_labels=train[:,1], 
                     test_data=train[:,0], 
                     test_labels=train[:,1], 
                     predictions=None):
  """
  Plots training data, test data and compares predictions.
  """
  plt.figure(figsize=(10, 7))

  # Plot training data in blue
  plt.scatter(train_data, train_labels, c="b", s=4, label="Training data")
  
  # Plot test data in green
  plt.scatter(test_data, test_labels, c="g", s=4, label="Testing data")

  if predictions is not None:
    # Plot the predictions in red (predictions were made on the test data)
    plt.scatter(test_data, predictions, c="r", s=4, label="Predictions")

  # Show the legend
  plt.legend(prop={"size": 14})

TypeError: list indices must be integers or slices, not tuple