In [1]:
import torch


In [2]:
scaler = torch.tensor(3) #scaler variable
vector = torch.tensor([1,2,3]) #vector variable
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) #matrix variable


In [3]:
print(scaler.ndim)  #prints the number of dimensions of the scaler variable
print(vector.ndim)  #prints the number of dimensions of the vector variable
print(matrix.ndim)  #prints the number of dimensions of the matrix variable

0
1
2


In [ ]:
matrix = torch.rand(size=(3,4))  #creates a 3x4 matrix with random values
print(matrix,matrix.dtype)

tensor([[0.8046, 0.0184, 0.8094, 0.6734],
        [0.3545, 0.9453, 0.7667, 0.6385],
        [0.5305, 0.6720, 0.9405, 0.2720]]) torch.float32


In [6]:
#zeros and ones
zeros = torch.zeros(size=(2,3))
ones = torch.ones(size=(2,3))
print(zeros)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# range of numbers!
range0_10 = torch.arange(start=0, end=10, step=2)
print(range0_10)

tensor([0, 2, 4, 6, 8])


In [8]:
#create a tensor of zero with shape of a tensor!
zeros_like = torch.zeros_like(input=range0_10)
print(zeros_like)

tensor([0, 0, 0, 0, 0])


In [11]:
#dtypes
float_16 = torch.tensor([1.0, 2.0, 11.0], dtype=torch.float16)
print(float_16.dtype)
print(float_16.device)
print(float_16.shape)

torch.float16
cpu
torch.Size([3])


In [13]:
#tensor operations +, *, - and matrix multiplication
tensor=torch.arange(1,4)
print(tensor)

tensor([1, 2, 3])


In [ ]:
print(tensor+10)  #adds 10 to each element in the tensor
print(tensor-2)
print(tensor*10)

tensor([11, 12, 13])
tensor([-1,  0,  1])


In [18]:
# matrix multiplication is done between (r*c) and (c*k) tensors
print(tensor@tensor)  #matrix multiplication
print(torch.matmul(tensor, tensor))  #matrix multiplication using torch.matmul

tensor(14)
tensor(14)


In [21]:
#finding min, max, mean, sum, std, var
print(torch.min(tensor))
print(torch.max(tensor))
print(tensor.type(torch.float32).mean())
print(torch.sum(tensor))
print(tensor.sum())

tensor(1)
tensor(3)
tensor(2.)
tensor(6)
tensor(6)


In [22]:
#positions of min and max
print(tensor.argmin())
print(tensor.argmax())

tensor(0)
tensor(2)


In [25]:
#change dtyep and device
tensor_float16= tensor.type(torch.float16)
# tensor_gpu = tensor.to("cuda")  #moves tensor to GPU if available
print(tensor_float16.dtype)
# print(tensor_gpu.device)

torch.float16


Reshaping, Stacing, Squeezing and Unsqueezing.

In [27]:
import torch
x = torch.arange(1,8)
print(x.shape)

torch.Size([7])


In [28]:
x_reshaped = x.reshape(1,7)  #reshapes x to 1 row and 7 columns
print(x_reshaped.shape)

torch.Size([1, 7])


In [29]:
z = x.view(1,7) #z is another way to reshape tensor x, but it shares the same memory as x. z is just a different view of x. changing z will change x and vice versa.
print(z.shape)
z[:,0] = 100
print(z)
print(x)  #x is also changed because z shares the same memory as x.

torch.Size([1, 7])
tensor([[100,   2,   3,   4,   5,   6,   7]])
tensor([100,   2,   3,   4,   5,   6,   7])


In [35]:
#stacking
print(x)
x_stack = torch.stack([x,x,x],dim=1)
print(x_stack)

tensor([100,   2,   3,   4,   5,   6,   7])
tensor([[100, 100, 100],
        [  2,   2,   2],
        [  3,   3,   3],
        [  4,   4,   4],
        [  5,   5,   5],
        [  6,   6,   6],
        [  7,   7,   7]])


In [34]:
print(x_reshaped)

tensor([[100,   2,   3,   4,   5,   6,   7]])
